repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-added-large-files
  - repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.12
#  - repo: https://github.com/pycqa/isort
#    rev: 5.12.0
#    hooks:
#      - id: isort
#        language_version: python3.11
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        language_version: python3.12
#        additional_dependencies: [flake8-bugbear==21.9.1]
        args: ["--extend-ignore=B008, C901, E501, F841, E203"]
